version: '3'

services:
  ui:
    build: ./UI
    ports:
      - "5002:5002"
    environment:
      - EEP1_URL=http://eep1:5000
    volumes:
      - ./UI:/app
    depends_on:
      - eep1
    networks:
      - app-network

  eep1:
    build: ./EEP1
    ports:
      - "5000:5000"
    environment:
      - IEP1_URL=http://iep1:5001
      - IEP2_URL=http://iep2:5004
      - IEP3_URL=http://iep3:5003
      - IEP4_URL=http://iep4:5005
    volumes:
      - ./EEP1:/app
    depends_on:
      - iep1
      - iep2
      - iep3
      - iep4
    networks:
      - app-network

  iep1:
    build: ./IEP1
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=gpt-4-1106-preview
    volumes:
      - ./IEP1:/app
    networks:
      - app-network

  iep2:
    build: ./IEP2
    ports:
      - "5004:5004"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-claude-3-7-sonnet-20250219}
    volumes:
      - ./IEP2:/app
    networks:
      - app-network

  iep3:
    build: ./IEP3
    ports:
      - "5003:5003"
    environment:
      - OAUTHLIB_INSECURE_TRANSPORT=1  # For development only
    volumes:
      - ./IEP3:/app
    networks:
      - app-network

  iep4:
    build: ./IEP4
    ports:
      - "5005:5005"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-claude-3-7-sonnet-20250219}
    volumes:
      - ./IEP4:/app
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  eep1_storage:
  eep1_persistence:
  iep1_storage:
  iep2_storage:
  prometheus_data:
  grafana_data:
