global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'iep1'
    static_configs:
      - targets: ['iep1:5001']

  - job_name: 'iep2'
    static_configs:
      - targets: ['iep2:5004']

  - job_name: 'iep3'
    static_configs:
      - targets: ['iep3:5003']

  - job_name: 'iep4'
    static_configs:
      - targets: ['iep4:5005']

  - job_name: 'eep1'
    static_configs:
      - targets: ['eep1:5000']

  - job_name: 'ui'
    static_configs:
      - targets: ['ui:5002'] 